[project]
name = "scraping"
version = "0.1.0"
description = "Data mining and processing"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "lxml>=5.3.2",
    "requests>=2.32.3",
]
